USE [master]
GO

/****** Object:  Database [CargoDB]    Script Date: 2023/12/12 22:41:38 ******/
CREATE DATABASE [CargoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CargoDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CargoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CargoDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CargoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CargoDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CargoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CargoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CargoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CargoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CargoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CargoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CargoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CargoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CargoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CargoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CargoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CargoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CargoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CargoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CargoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CargoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CargoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CargoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CargoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CargoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CargoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CargoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CargoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CargoDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CargoDB] SET  MULTI_USER 
GO

ALTER DATABASE [CargoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CargoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CargoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CargoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CargoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CargoDB] SET QUERY_STORE = OFF
GO

USE [CargoDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CargoDB] SET  READ_WRITE 
GO

